name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (with submodules)
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies (CMake and G++)
      run: sudo apt-get update && sudo apt-get install cmake g++ -y

    - name: Configure CMake project
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run unit + integration tests
      run: ./build/board_tests || ./out/build/x64-Debug/board_tests.exe  # one of these will work depending on platform
